//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntMe.Basics.Factions.Ants {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AntGeneratorFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AntGeneratorFiles() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AntMe.Basics.Factions.Ants.AntGeneratorFiles", typeof(AntGeneratorFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aaliyah
        ///Aarushi
        ///Abbey
        ///Abbi
        ///Abbie
        ///Abby
        ///Abelina
        ///Abi
        ///Abia
        ///Abigail
        ///Aby
        ///Acacia
        ///Ada
        ///Adalia
        ///Adalyn
        ///Addie
        ///Addison
        ///Adelaide
        ///Adele
        ///Adelia
        ///Adelina
        ///Adeline
        ///Adina
        ///Adreanna
        ///Adriana
        ///Adrianna
        ///Adrianne
        ///Adrienne
        ///Aerona
        ///Afra
        ///Agatha
        ///Aggie
        ///Agnes
        ///Aida
        ///Aileen
        ///Aimee
        ///Aine
        ///Ainsley
        ///Aischa
        ///Aisha
        ///Aisling
        ///Ajlin
        ///Alaina
        ///Alana
        ///Alanis
        ///Alanna
        ///Alannah
        ///Alayah
        ///Alayna
        ///Alba
        ///Albertine
        ///Alea
        ///Aleah
        ///Alecia
        ///Aleisha
        ///Alejandra
        ///Aleksandra
        ///Alena
        ///Alessa
        ///Alessandra
        ///Alessia
        ///Alex
        ///Alexa
        ///Alexandra
        ///A [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string femaleNames {
            get {
                return ResourceManager.GetString("femaleNames", resourceCulture);
            }
        }
    }
}
